language: java

jdk:
  - oraclejdk8
os:
  - linux

sudo: required

before_install:
  - ./travis/travis_install_consul.sh

install:
  - ./travis/install.sh

script:
  - ./consul agent -dev
  - mvn clean -pl archetype-helloworld test
  - mvn clean -pl archetype-helloworld-scala test

after_failure:
  - cat archetype-helloworld/target/surefire-reports/*.txt

cache:
  directories:
    - $HOME/.m2

services:
  - mysql
  - mongodb
  - redis-server
  - rabbitmq