language: java

jdk:
  - oraclejdk7
os:
  - linux

sudo: required

before_install:
  - curl -O https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/tar/elasticsearch/2.3.4/elasticsearch-2.3.4.tar.gz && tar zxvf elasticsearch-2.3.4.tar.gz && elasticsearch-2.3.4/bin/elasticsearch

install:
  - ./travis/install.sh

script:
  - mvn clean -pl archetype-helloworld test

after_failure:
  - cat archetype-helloworld/target/surefire-reports/*.txt

cache:
  directories:
    - $HOME/.m2

services:
  - mysql
  - mongodb
  - redis-server