language: java

jdk:
  - oraclejdk8
os:
  - linux

sudo: required

before_install:
  - ./travis/install_consul.sh
  - ./travis/install_hbase.sh

install:
  - ./travis/install.sh

script:
  - nohup ./consul agent -dev -bind=127.0.0.1 &
  - mvn install -N
  - mvn clean -pl archetype-common install
  - if [[ "$TEST_HELLO" == "TRUE" ]]; then mvn clean -pl archetype-helloworld test; fi
  - if [[ "$TEST_HADOOP" == "TRUE" ]]; then mvn clean -pl archetype-hadoop test; fi
  - if [[ "$TEST_SCALA" == "TRUE" ]]; then mvn clean -pl archetype-hello-scala test; fi

after_failure:
  - cat archetype-helloworld/target/surefire-reports/*.txt

notifications:
  email:
    - guoxu1231@foxmail.com

cache:
  directories:
    - $HOME/.m2

services:
  - mysql
  - mongodb
  - redis-server
  - rabbitmq