language: java

jdk:
  - oraclejdk7
os:
  - linux

install:
  - ./travis/install.sh

script:
  - mvn clean -pl archetype-helloworld test

after_failure:
  - cat archetype-helloworld/target/surefire-reports/*.txt

cache:
  directories:
    - $HOME/.m2

services:
  - mysql
  - mongodb
  - redis-server