language: java

jdk:
  - oraclejdk8
os:
  - linux

sudo: required

before_install:
  - ./travis/install_consul.sh
  - ./travis/install_hbase.sh

install:
  - ./travis/install.sh

script:
  - nohup ./consul agent -dev &
  - mvn clean -pl archetype-helloworld test
  - mvn clean -pl archetype-helloworld-scala test

after_failure:
  - cat archetype-helloworld/target/surefire-reports/*.txt

cache:
  directories:
    - $HOME/.m2

services:
  - mysql
  - mongodb
  - redis-server
  - rabbitmq