language: java

jdk:
  - openjdk7
os:
  - linux

install:
  - ./ci_script/install.sh

script:
  - mvn clean -pl archetype-helloworld test

after_failure:
  - cat target/surefire-reports/*.txt

cache:
  directories:
    - $HOME/.m2

services:
  - mysql